package org.models;
// Generated 02-ago-2014 15:39:50 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private int id;
     private Usuario usuarioByIdUsuarioSolicita;
     private Usuario usuarioByIdUsuarioConductor;
     private Usuario usuarioByIdUsuarioCrea;
     private String origen;
     private String destino;
     private Date FSalida;
     private Date FLlegada;
     private String hospedaje;
     private Boolean estado;
     private String novedades;

    public Solicitud() {
    }

	
    public Solicitud(int id) {
        this.id = id;
    }
    public Solicitud(int id, Usuario usuarioByIdUsuarioSolicita, Usuario usuarioByIdUsuarioConductor, Usuario usuarioByIdUsuarioCrea, String origen, String destino, Date FSalida, Date FLlegada, String hospedaje, Boolean estado, String novedades) {
       this.id = id;
       this.usuarioByIdUsuarioSolicita = usuarioByIdUsuarioSolicita;
       this.usuarioByIdUsuarioConductor = usuarioByIdUsuarioConductor;
       this.usuarioByIdUsuarioCrea = usuarioByIdUsuarioCrea;
       this.origen = origen;
       this.destino = destino;
       this.FSalida = FSalida;
       this.FLlegada = FLlegada;
       this.hospedaje = hospedaje;
       this.estado = estado;
       this.novedades = novedades;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuarioByIdUsuarioSolicita() {
        return this.usuarioByIdUsuarioSolicita;
    }
    
    public void setUsuarioByIdUsuarioSolicita(Usuario usuarioByIdUsuarioSolicita) {
        this.usuarioByIdUsuarioSolicita = usuarioByIdUsuarioSolicita;
    }
    public Usuario getUsuarioByIdUsuarioConductor() {
        return this.usuarioByIdUsuarioConductor;
    }
    
    public void setUsuarioByIdUsuarioConductor(Usuario usuarioByIdUsuarioConductor) {
        this.usuarioByIdUsuarioConductor = usuarioByIdUsuarioConductor;
    }
    public Usuario getUsuarioByIdUsuarioCrea() {
        return this.usuarioByIdUsuarioCrea;
    }
    
    public void setUsuarioByIdUsuarioCrea(Usuario usuarioByIdUsuarioCrea) {
        this.usuarioByIdUsuarioCrea = usuarioByIdUsuarioCrea;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public Date getFSalida() {
        return this.FSalida;
    }
    
    public void setFSalida(Date FSalida) {
        this.FSalida = FSalida;
    }
    public Date getFLlegada() {
        return this.FLlegada;
    }
    
    public void setFLlegada(Date FLlegada) {
        this.FLlegada = FLlegada;
    }
    public String getHospedaje() {
        return this.hospedaje;
    }
    
    public void setHospedaje(String hospedaje) {
        this.hospedaje = hospedaje;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getNovedades() {
        return this.novedades;
    }
    
    public void setNovedades(String novedades) {
        this.novedades = novedades;
    }




}


